routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/migrate', function () {
    Artisan::call('migrate');
    return 'Migrated';
});
Route::get('/clear-cache', function () {
    Artisan::call('optimize:clear');
    return 'Cleared';
});

Route::get('/link-storage', function () {
    Artisan::call('storage:link');
    return 'Storage';
});

Route::get('/seeder', function () {
    Artisan::call('db:seed');
    return 'seeder';
});

Route::group(['namespace' => 'App\Http\Controllers'],function(){

    #Admin Routes
    Route::get('/login', 'AuthController@showLogin')->name('login');
    Route::group(['prefix'=>'admin-panel','as'=>'admin.'], function()
    {
        Route::post('hire_form','HireFormController@store')->name('hireForm');
        Route::post('/login', 'AuthController@login')->name('login');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth:admin'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            
            Route::get('wallet-status/{wallet}/{status}','WalletController@status')->name('wallet.status');

            Route::resources([
                'vehicle_type' => 'VehicleTypeController',
                'make' => 'MakeController',
                'vehicle_model' => 'VehicleModelController',
                'rent' => 'RentController',
                'hire' => 'HireController',
                'admin' => 'AdminController',
                'user' =>'UserController',
                'dpr' =>'DprController',
                'slider' => 'SliderController',
                'testimonial' => 'TestimonialController',
                'page' =>'PageController',
                'site_setting' => 'SiteSettingController',
                'wallet'=>'WalletController',
                // 'hire_form'=>'HireFormController',
            ]);
        });
    });

    #Vendor Routes
    Route::group(['prefix'=>'vendor-panel','as'=>'vendor.','namespace'=>'Vendor'], function()
    {
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login')->name('login.post');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            Route::get('company_edit/{user}','UserController@company_edit')->name('company_edit');
            Route::get('bank_edit/{user}','UserController@bank_edit')->name('bank_edit');
            Route::resources([
                'rent'  => 'RentController',
                'hire'  => 'HireController',
                'admin' => 'AdminController',
                'user'  =>'UserController',
                'dpr'   =>'DprController',
                'wallet'=>'WalletController',
            ]);
        });
    });

    
    #FrontEnd Routes
    Route::group(['namespace' => 'Web'], function() {
        Route::get('/','HomeController@index')->name('home');
        Route::get('Contact','ContactController@contact')->name('Contact');
        Route::get('Vendor/signin','VendorSignController@vendorsign')->name('Vendor.signin');
        Route::post('Vendor/store','VendorSignController@store')->name('Vendor.store');
        Route::get('rentalProduct','ProductController@rentalProduct')->name('rentalProduct');
        
        Route::group(['middleware' => 'vendor'], function(){
            Route::get('hire/{rent}','HireController@hire')->name('hire');
            Route::post('hire','HireController@store')->name('hire.store');
        });
        
        Route::get('{page:slug}','PageController@show')->name('page.show');
    });


});

resources/views/frontend/pages/contact.blade.php
@extends('frontend.layout.app')

@section('site_title','Contact')

@section('content')

<div class="about-header">
    <img src="{{ url('frontend/images/slideshow-1.jpg') }}" alt="">
    <div class="overlay">
        <div class="page-header-title">Contact Us</div>
    </div>
</div>

<div class="container py-5">
    <div class="contact-block">
        <div class="contact-grid">
            <div class="first-col">
                <div class="sidebar">
                    <div class="contact-detail">
                        <h4 class="title-contact">Contact Details</h4>
                        <ul class="contact-list">
                            <li class="contact-list-item ">
                                <div class="contact-list-item_icon">
                                    <i class="fa-solid fa-location-dot"></i>
                                </div>
                                <div class="contact-list-item_desc">
                                    <div class="contact-list-item_label">Office Address</div>
                                    <div class="contact-list-item_content">{{ $siteSetting->address }}</div>
                                </div>
                            </li>
                            <div class="border-bootom-width"></div>
                            <li class="contact-list-item">
                                <div class="contact-list-item_icon">
                                    <i class="fa-solid fa-phone-volume"></i>
                                </div>
                                <div class="contact-list-item_desc">
                                    <div class="contact-list-item_label">Contact No.</div>
                                    <div class="contact-list-item_content"><a href="tel:+91{{ $siteSetting->phone }}">+91 {{ $siteSetting->phone }}</a></div>
                                </div>
                            </li>
                            <div class="border-bootom-width"></div>
                            <li class="contact-list-item">
                                <div class="contact-list-item_icon">
                                    <i class="fa-solid fa-location-dot"></i>
                                </div>
                                <div class="contact-list-item_desc">
                                    <div class="contact-list-item_label">send us Mail</div>
                                    <div class="contact-list-item_content"><a href="mailto:{{ $siteSetting->email }}">{{ $siteSetting->email }}</a></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="second-col">
                <div class="contact-form">
                    <div class="contact-form_title">
                        <h2>Send a Message</h2>
                    </div>
                    <div class="form-content">
                        <form action="" method="post">
                            <div class="row mb-3">
                                <div class="col-6">
                                    {{ Form::text('name',null,['class' => 'form-control py-3','placeholder'=>'Name *']) }}
                                </div>
                                <div class="col-6">
                                    {{ Form::email('email', null,['class' => 'form-control py-3', 'placeholder' => 'Email *']) }}
                                </div>
                            </div>
                            <div class="col-12 mb-3">
                                {{ Form::text('subject',null,['class' => 'form-control py-3', 'placeholder' => 'Subject']) }}
                            </div>

                            <div class="col-12">
                                {{ Form::textarea('message',null,['class' => 'form-control py-3', 'placeholder' => 'Message', 'rows' => '4']) }}
                            </div>

                            <button type="submit" class="submit-form-btn">Send Message <i class="fa-solid fa-arrow-right-to-bracket px-2"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="map">
        <iframe src="{{ $siteSetting->map }}" width="100%" height="400" style="border:1px solid
         #cccc;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

@endsection

resources/views/frontend/pages/hire.blade.php
@extends('frontend.layout.app')

@section('site_title','Hire')

@section('content')

<div class="about-header">
    <img src="{{ url('frontend/images/slideshow-1.jpg') }}" alt="">
    <div class="overlay">
        <div class="page-header-title">Hire</div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-7 py-5">
            <div class="product-img">
                <img src="{{ url("image/rents/". $rent->image) }}" class="card-img-top" alt="{{ $rent->vehicle_model->name }} Image" style="height: 280px; object-fit: cover; border-radius: 12px">
            </div>
        </div>
        <div class="col-sm-5 py-5">
            <div class="hire-title">
                <h2>
                    <span>{{ $rent->vehicle_model->name }}</span>
                    <span>{{ $rent->vehicle_model->make->name }}</span>
                    <span>{{ $rent->vehicle_type }}</span>
                </h2>
            </div>

            <div class="col-sm-12">
                {{ Form::open(['url' =>route('hire.store'),'files'=>true,'method'=>'post','id'=>'checkout-form']) }}
                    <div class="equipment-detail mt-2">
                        <table>
                            <tbody>
                                <tr>
                                    <td>Brand</td>
                                    <td>{{ $rent->vehicle_model->make->name }}</td>
                                </tr>
                                <tr>
                                    <td>Manufacturig Year</td>
                                    <td>{{ $rent->year }}</td>
                                </tr>
                                <tr>
                                    <td>Contact Person</td>
                                    <td>{{ $rent->contact_person }}</td>
                                </tr>
                                <tr>
                                    <td>Vehicle Number</td>
                                    <td>{{ $rent->vehicle_number }}</td>
                                </tr>
                                <tr>
                                    <td>Avg Km/Ltr</td>
                                    <td>{{ $rent->avg_kml }}</td>
                                </tr>
                                <tr>
                                    <td>Avg Km/hr</td>
                                    <td>{{ $rent->avg_kmh }}</td>
                                </tr>
                                <tr>
                                    <td>Last Km</td>
                                    <td>{{ $rent->last_km }}</td>
                                </tr>
                                <tr>
                                    <td>Price Type</td>
                                    <td>{{ $rent->price_type }}</td>
                                </tr>
                                <tr>
                                    <td>Price</td>
                                    <td id="price">{{ $rent->price }}</td>
                                </tr>

                                <input type="hidden" name="rent_id" value="{{ $rent->id }}">
                                <input type="hidden" name="txn_id" id="txnId" value="{{ $rent->txn_id }}">

                                <tr>
                                    <td>No. of {{$rent->price_type }}</td>
                                    <td>
                                        <input type="text" id="num" name="duration" onkeyup="calQty(this.value)" value="1"  min="1" max="100" step="1" for="price"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Total Price</td>
                                    <td id="totalAmount">{{ $rent->price }} </td>
                                </tr>
                                <tr>
                                    <td>Transportation</td>
                                    <td>
                                        <input type="radio" name="user" id="">By User &nbsp;
                                        <input type="radio" name="company" id="">By Company
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-sm-4 mt-4">
                        <div class="hire-submit">
                            <button type="button" class="btn buy_now btn-secondary">Preced To Pay</button>
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts') 
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<script>

    function calQty(qty) {
        let price = document.getElementById('price').innerText;
        price = parseFloat(price);
        document.getElementById('totalAmount').innerText = price * qty;
    }
    $(function() {
    });

    $(function() {
        $('body').on('click','.buy_now', function(e) {

            var totalAmount = $('#totalAmount').text();

            var options = {
			"key": "rzp_test_7YUA5jcBdwHcnC", // "rzp_test_is9f8HAHz5kblj",
			"amount": (totalAmount * 100), // 2000 paise = INR 20
			"name": "Rent and Hire",
			"description": "Payment",
			"image": "{{ url("storage/".$siteSetting->logo) }}",
			"handler": function(response) {
				$('#txnId').val(response.razorpay_payment_id);
				$('#checkout-form').trigger('submit');
			},
			"prefill": {
				"contact": $('#phone').val(),
				"email": $('#email').val(),
			},
			"theme": {
				"color": "linear-gradient(-145deg, rgba(219,138,222,1) 0%, rgba(246,191,159,1) 100%)"
			}
		};
        var rzp1 = new Razorpay(options);
		rzp1.open();
		e.preventDefault();
        });
    });
</script>
@endpush

resources/views/frontend/pages/hiredetail.blade.php
@extends('frontend.layout.app')

@section('site_title','Sucess')

@section('content')

<div class="hire-body">
    <header class="hire-header">
        <h1 class="hire-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
    </header>
    
    <div class="container">
        <div class="row">
            <div class="main-content text-center">
                <i class="fa fa-check main-content__checkmark"></i>
                <div class="col-sm-4 mb-4 m-auto">
                    <div class="equipment-detail mt-2 text-start">
                        <table>
                            <tbody>
                                <tr>
                                    <td>Make</td>
                                    <td>{{ $rent->vehicle_model->make->name }}</td>
                                </tr>
                                <tr>
                                    <td>Manufacturig Year</td>
                                    <td>{{ $rent->year }}</td>
                                </tr>
                                <tr>
                                    <td>Contact Person</td>
                                    <td>{{ $rent->contact_person }}</td>
                                </tr>
                                <tr>
                                    <td>Price Type</td>
                                    <td>Per {{ $hire->price_type }}</td>
                                </tr>
                                <tr>
                                    <td>Price</td>
                                    <td>{{ $hire->price }}</td>
                                </tr>
                                <tr>
                                    <td>Duration</td>
                                    <td>{{ $hire->duration }} {{ $hire->price_type }}</td>
                                </tr>
                                <tr>
                                    <td>Total Price</td>
                                    <td>{{ $hire->total }}</td>
                                </tr>
                                <tr>
                                    <td>Transaction Id</td>
                                    <td>{{ $hire->txn_id }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    
        </div>
    </div>
</div>

@endsection

resources/views/frontend/pages/homepage.blade.php
@extends('frontend.layout.app')

@section('site_title','Rent and Hire')

@section('content')

<section class="slider">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner">
      @foreach ($sliders as $key => $slider )
      <div class="carousel-item @if ($key == '0') active 
        
      @endif ">
        <img src="{{ url("storage/".$slider->image) }}" style="object-fit: cover;height:460px;" class="d-block w-100" alt="slider image">
      </div>
        
      @endforeach
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

{{-- Start Card --}}

<section class="card py-5">
  <div class="container">

    <div class="section-title">
      <div class="title-h2">For Rent</div>
    </div>

    <div class="row">

      @foreach ($rents as $i => $rent)
        <div class="col-sm-4 py-2">
          <div class="card">
            <img src="{{ url("image/rents/". $rent->image) }}" class="card-img-top" style="height: 180px; object-fit: cover" alt="{{ $rent -> vehicle_model->make-> name}}">
            <div class="card-body">
              <h5 class="card-title">{{ $rent -> vehicle_model -> name}} {{ $rent -> vehicle_model->make-> name}}</h5>
              <p class="card-text py-4">
                <strong>Price</strong> : ₹ {{ $rent -> price}} / {{ $rent -> price_type}} <br><br>
                <strong>Vehicle No.</strong> : {{ $rent->vehicle_number }} <br><br>
                <strong>Avg: </strong> {{ $rent->avg_kml }} Kml, {{ $rent->avg_kmh }} Kmh <br><br>
                <strong>Last KM: </strong> {{ $rent->last_km }} <br><br>
                <strong>Manufacturing Year</strong> : {{ $rent -> year}} <br><br>
                <strong>Vehicle Location</strong> : {{ $rent -> location}}
              </p>
              <a href="{{ route('hire',$rent->id) }}" class="hire-btn">Hire Now</a>
            </div>
          </div>
        </div>
      @endforeach
    </div>

    <div class="text-center py-4">
      <a href="{{ route('rentalProduct') }}" type="submit" class="hire-btn">Show More ...</a>
    </div>
    
  </div>
</section>

{{-- Cart End --}}

{{-- Testimonial start --}}
{{-- 
<section class="testimonials">
  <div class="container py-5">
    <div class="section-title">
      <div class="title-h2">
        Customers Thoughts
      </div>
    </div>
    <div class="wrapper">
      @foreach ($testimonials as $i => $t)
        <div class="col-sm-4">
          <i class="fa-solid fa-quote-left"></i>
          <p>{{ $t->short_description }}</p>
          <div class="content">
            <div class="info">
              <div class="name">{{ $t->name }}</div>
            </div>
          </div>
        </div>
      @endforeach
    </div>
  </div>
</section> --}}

<div class="container mb-5">


  <div class="section-title py-3">
    <div class="title-h2">
      Customers Thoughts
    </div>
  </div>
  
  <div class="row row-cols-1 row-cols-md-3 g-4 py-3">

    @foreach ($testimonials as $i => $t)

    <div class="col">
      <div class="card h-100">
        {{-- <img src="..." class="card-img-top" alt="..."> --}}
        <div class="card-body">
          <h5 class="card-title">{{ $t->name }}</h5>
          <p class="card-text">{{ $t->short_description }}</p>
        </div>
        {{-- <div class="card-footer">
          <small class="text-muted">{{ $t->name }}</small>
        </div> --}}
      </div>
    </div>
    
    @endforeach

  </div>

</div>  

{{-- Testimonial End --}}

{{-- Hire requirement form --}}

<section class="requirement-form">
  <div class="container">
    <div class="form-section">
      <div class="row">
        <div class="col-sm-4">
       
            <img src="frontend/images/contactus-banner.png" alt="" style="width:100%;margin-top:97px">
         
        </div>
        <div class="col-sm-8">
          <div class="header py-3">
            <h3>Hire Requirement</h3>
          </div>
          @include('vendor.template.messages')
          <div class="card mb-5">
            {{ Form::open(['url' => route('admin.hireForm'),'files'=>true,'method'=>'post','novalidate'=>true]) }}
            <div class="row p-5">
              <div class="col-sm-6">

                <div class="mb-4">
  
                  {{ Form::select('make_id',$makes,null,
                    [
                      'class'=>'form-select py-2',
                      'placeholder'=>'Select Vehicle'
                    ]
                    ) 
                  }}
                </div>
                <div class="mb-3">
                  {{ Form::text('name','',['class'=>'form-control py-2','placeholder'=>'Name']) }}
                </div>
                <div class="mb-3">
                  {{ Form::email('mail','',['class'=>'form-control py-2','placeholder'=>'e-Mail']) }}
                </div>
              </div>
              <div class="col-sm-6">
                <div class="mb-3">
                  {{ Form::textarea('message',null,['class'=>'form-control py-4','placeholder' =>'Message','rows'=>'5']) }}
                </div>
              </div>
              <div>
                <button class="btn btn-primary">Send Message</button>
              </div>
            </div>
            {{ Form::close() }}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{{-- Hire requirement form End--}}

@endsection

resources/views/frontend/pages/page.blade.php
@extends('frontend.layout.app')

@section('site_title', $page->title)

@section('content')

{{-- <section class="header-about" style="background-image: url(frontend/images/ezgif.com-gif-maker.jpg); height:250px;">
    <div class="about-head-content">
        <div class="about-head-title">About Us</div>
        <div class="about-head-breadcrumb">
            <ul class="breadcrumb">
                <li>
                    <a href="">Home</a>
                </li>
                <li>
                    <span>Our Organisation</span>
                </li>
            </ul>
        </div>
    </div>
</section> --}}

<div class="about-header">
    <img src="{{ url("storage/".$page->image) }}" alt="">
    <div class="overlay">
        <div class="page-header-title">{{ $page->title }}</div>
    </div>
</div>

<section class="about">
    <div class="container">
        <div class="about-para py-4">
            {!! $page->description !!}
        </div>
    </div>
</section>

@endsection

resources/views/frontend/pages/vendor_login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vendor - login | Rent & Hire</title>
    <link rel="stylesheet" href="{{ url('frontend/css/style.css') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="frontend/images/Logo.png">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <div class="login-page">
        <div class="login-header">
            <div class="container-fluid">
                <div class="login-title">
                    <a href="">Rent &  Hire - Vendor Registration</a>
                </div>
            </div>
        </div>
        <div class="login-content d-flex align-items-center flex-wrap justify-content-center" style="background : url('http://renthire.in/assets/images/banner.jpg'); background-size: cover">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6">
                        <div class="login-vendor bg-white box-shadow">
                            <div class="login-vendor-title">
                                <h2 class="text-center text-danger">Vendor Login Panel</h2>
                                <div style="color: red;font-size: 15px;text-align: center !important;margin-top: 16px;"></div>
                            </div>
                            <form action="" method="post">
                                <div class="input-group custom mb-3">
                                    <input type="text" name="email" class="form-control form-control-lg" placeholder="Email Id">
                                </div>
                                <div class="input-group custom mb-3">
                                    <input type="password" name="password" class="form-control form-control-lg" placeholder="********">
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-input-checkbox" name="" id="">
                                            <label for="" class="custom-label">Remember Me</label>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="forgot-pass">
                                            <a href="">Forgot Password</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="input-group mb-0">
                                            <div class="vendor-login-button" type="submit">Login</div>
                                        </div>
                                        <div class="font-16 weight-600 pt-10 pb-10 text-center" data-color="#707373" style="color: rgb(112, 115, 115);">OR</div>
                                        <div class="input-group mb-0">
                                            {{-- <div class="vendor-register-button" type="submit">Register</div> --}}
                                            <a href="{{ route('Vendor.signin') }}" type="button" class="vendor-register-button text-decoration-none">Register</a>
                                        </div>
                                    </div>
                                </div>
                            </form>

                            

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>