routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/migrate', function () {
    Artisan::call('migrate');
    return 'Migrated';
});
Route::get('/clear-cache', function () {
    Artisan::call('optimize:clear');
    return 'Cleared';
});

Route::get('/link-storage', function () {
    Artisan::call('storage:link');
    return 'Storage';
});

Route::get('/seeder', function () {
    Artisan::call('db:seed');
    return 'seeder';
});

Route::group(['namespace' => 'App\Http\Controllers'],function(){

    #Admin Routes
    Route::get('/login', 'AuthController@showLogin')->name('login');
    Route::group(['prefix'=>'admin-panel','as'=>'admin.'], function()
    {
        Route::post('hire_form','HireFormController@store')->name('hireForm');
        Route::post('/login', 'AuthController@login')->name('login');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth:admin'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            
            Route::get('wallet-status/{wallet}/{status}','WalletController@status')->name('wallet.status');

            Route::resources([
                'vehicle_type' => 'VehicleTypeController',
                'make' => 'MakeController',
                'vehicle_model' => 'VehicleModelController',
                'rent' => 'RentController',
                'hire' => 'HireController',
                'admin' => 'AdminController',
                'user' =>'UserController',
                'dpr' =>'DprController',
                'slider' => 'SliderController',
                'testimonial' => 'TestimonialController',
                'page' =>'PageController',
                'site_setting' => 'SiteSettingController',
                'wallet'=>'WalletController',
                // 'hire_form'=>'HireFormController',
            ]);
        });
    });

    #Vendor Routes
    Route::group(['prefix'=>'vendor-panel','as'=>'vendor.','namespace'=>'Vendor'], function()
    {
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login')->name('login.post');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            Route::get('company_edit/{user}','UserController@company_edit')->name('company_edit');
            Route::get('bank_edit/{user}','UserController@bank_edit')->name('bank_edit');
            Route::resources([
                'rent'  => 'RentController',
                'hire'  => 'HireController',
                'admin' => 'AdminController',
                'user'  =>'UserController',
                'dpr'   =>'DprController',
                'wallet'=>'WalletController',
            ]);
        });
    });

    
    #FrontEnd Routes
    Route::group(['namespace' => 'Web'], function() {
        Route::get('/','HomeController@index')->name('home');
        Route::get('Contact','ContactController@contact')->name('Contact');
        Route::get('Vendor/signin','VendorSignController@vendorsign')->name('Vendor.signin');
        Route::post('Vendor/store','VendorSignController@store')->name('Vendor.store');
        Route::get('rentalProduct','ProductController@rentalProduct')->name('rentalProduct');
        
        Route::group(['middleware' => 'vendor'], function(){
            Route::get('hire/{rent}','HireController@hire')->name('hire');
            Route::post('hire','HireController@store')->name('hire.store');
        });
        
        Route::get('{page:slug}','PageController@show')->name('page.show');
    });


});

app/Http/Controllers/Api/VehicleTypeController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\VehicleType;
use Illuminate\Http\Request;

class VehicleTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $vehicle_Type = VehicleType::with(['make', 'make.vehicle_model']);

        if(!empty($request->type) && $request->type == 'all')
        {
            $vehicle_Type = $vehicle_Type->pluck('name','id');
        }
        else
        {
            $vehicle_Type = $vehicle_Type->get();
        }
        
        return response()->json( $vehicle_Type );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\VehicleType  $vehicleType
     * @return \Illuminate\Http\Response
     */
    public function show(VehicleType $vehicle_Type)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\VehicleType  $vehicleType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, VehicleType $vehicle_Type)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\VehicleType  $vehicleType
     * @return \Illuminate\Http\Response
     */
    public function destroy(VehicleType $vehicle_Type)
    {
        //
    }
}

app/Http/Controllers/VehicleTypeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\VehicleType;
use Illuminate\Http\Request;

use App\Http\Requests\VehicleTypeRequest;

class VehicleTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        
        $vehicle_types = VehicleType::paginate(10);
        return view('backend.pages.vehicle_type.index', ['vehicle_types' => $vehicle_types]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.vehicle_type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VehicleTypeRequest $request)
    {
        $vehicle_type = new VehicleType();

        $vehicle_type->name = $request->name;
        $vehicle_type->slug = $request->slug;
        $vehicle_type->save();

        return redirect(route('admin.vehicle_type.index'))->with('success', 'Your data has been Stored in Database.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\vehicle_type  $vehicle_type
     * @return \Illuminate\Http\Response
     */
    public function show(vehicle_type $vehicle_type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\vehicle_type  $vehicle_type
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, vehicle_type $vehicle_type)
    {
        $request->replace($vehicle_type->toArray());
        $request->flash();

        $data = compact('vehicle_type');
        return view('backend.pages.vehicle_type.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\vehicle_type  $vehicle_type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, vehicle_type $vehicle_type)
    {
        $vehicle_type->name = $request->name;
        $vehicle_type->slug = $request->slug;
        $vehicle_type->save();

        return redirect(route('admin.vehicle_type.index'))->with('success', 'Your data has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\vehicle_type  $vehicle_type
     * @return \Illuminate\Http\Response
     */
    public function destroy(vehicle_type $vehicle_type)
    {
        if(! empty($vehicle_type->image)){
            $dir = public_path('image/vehicle_types' .$vehicle_type->image);
            if(file_exists($dir))unlink($dir);
            $dir = public_path('images/vehicle_types/thumbnail' .$vehicle_type->image);
            if(file_exists($dir));
        }

        $vehicle_type->delete();
        return redirect(route('admin.vehicle_type.index'))->with('success', 'Your data has been deleted.');
    }
}

resources/views/backend/pages/vehicle_type/create.blade.php
@extends('backend.layout.inner')

@section('site_title','Vehicle Type')

@section('content')

<div class="container-fluid py-4">
        <div class="bg-white">
           
            <h2>Add Vehicle Type</h2>

            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard') }}">Dashboard</a> 
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.vehicle_type.index') }}">Vehicle Type</a> 
                </li>
                <li class="breadcrumb-item active">Add Vehicle Type</li>
            </ol>

        </div>
        {!! Form::open
            ([
                'url' => route('admin.vehicle_type.store'), 
                'method' => 'post',
                'novalidate' => true
            ]) 
        !!}
        @include('backend.pages.vehicle_type.form')

        <div class="pt-3">
        
            <button type="submit" class="btn btn-primary">Save</button>
        
            <button type="reset" class="btn btn-secondary">Reset</button>

    
        </div>


        {!! form::close() !!}
    </div>

@endsection

resources/views/backend/pages/vehicle_type/edit.blade.php
@extends('backend.layout.inner')

@section('site_title','Vehicle Type')

@section('content')

<div class="container-fluid">
    <div class="bgwhite pt-5">

        <h2>Edit vehicle Type</h2>

        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item">
                <a href="{{route('admin.dashboard')}}">Dashboard</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{route('admin.vehicle_type.create')}}">Vehicle Type</a>
            </li>
            <li class="breadcrumb-item active">Edit Vehicle Type</li>
        </ol>
    </div>

    {!! Form::open
        ([
            'url' => route('admin.vehicle_type.update',
            [$vehicle_type->id]), 
            'method' => 'put'
        ]) 
    !!}
    @include('backend.pages.vehicle_type.form')

    <div>
        
            <button type="submit" class="btn btn-primary">Update</button>

        
        
            <button type="reset" class="btn btn-secondary">Reset</button>

        
    </div>

    {!! Form::close() !!}
</div>

@endsection

resources/views/backend/pages/vehicle_type/form.blade.php
@include('backend.template.messages')
<div class="row pt-5 bg-white">
    <div class="col-8  text-dark">
        
            
        <div class="mb-3">
            {!! Form::label('name') !!}
            {!! Form::text('name',null, ['class' => 'form-control title', 'placeholder' => 'Enter','data-target' => '#slug','required' => 'required']) !!}
        </div>
            
            
        
        <div class="mb-3">
            {!! Form::label('slug', 'SEO Title') !!}
            {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Enter Slug','required' =>'required']) !!}
        </div>
        

    </div>
        
        
</div>

resources/views/backend/pages/vehicle_type/index.blade.php
@extends('backend.layout.inner')

@section('site_title','Vehicle Type')

@section('content')

<div class="container-fluid py-4">
    <div class="bgwhite">
        
        <h2>View Vehicle Type</h2>

        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard') }}">Dashboard</a> 
            </li>
            <li class="breadcrumb-item">
                <a href="{{ route('admin.vehicle_type.create') }}">Vehicle Type</a> 
            </li>
            <li class="breadcrumb-item active">View Vehicle Type</li>
        </ol>
    </div>

    <!-- <nav class="navbar navbar-light bg-light mb-4">
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </nav> -->
    @include('backend.template.messages')
    @if($vehicle_types->isEmpty())
    <div>

    </div>
    @else
    <div>
      {{ $vehicle_types->firstItem() }} to {{ $vehicle_types->lastItem() }} form {{ $vehicle_types->total() }} are Showing
    </div>

    <table class="table table-striped py-5">
  <thead>
    <tr>
      <th>Sr .No</th>
      <th>Name</th>
      <th>Slug</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach($vehicle_types as $index => $vehicle_type)
    <tr>
      <th>{{ $index + $vehicle_types -> firstItem() }}</th>
      <td>{{ $vehicle_type -> name}}</td>
      
      <td>{{ $vehicle_type -> slug}}</td>

      <td>
        <div class="dropdown">
          <button class="btn btn-link" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{route('admin.vehicle_type.edit',[$vehicle_type->id]) }}">Edit</a>
            {{ Form::open(['url' => route('admin.vehicle_type.destroy', [$vehicle_type->id]), 'method' => 'DELETE', 'class' => 'delete-form']) }}
            <button type="button" class="delete-btn dropdown-item">Delete</button>
            {{ Form::close() }}
          
          </div>
        </div>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
{{ $vehicle_types->links("pagination::bootstrap-5") }}
@endif
</div>

@endsection