routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/migrate', function () {
    Artisan::call('migrate');
    return 'Migrated';
});
Route::get('/clear-cache', function () {
    Artisan::call('optimize:clear');
    return 'Cleared';
});

Route::get('/link-storage', function () {
    Artisan::call('storage:link');
    return 'Storage';
});

Route::get('/seeder', function () {
    Artisan::call('db:seed');
    return 'seeder';
});

Route::group(['namespace' => 'App\Http\Controllers'],function(){

    #Admin Routes
    Route::get('/login', 'AuthController@showLogin')->name('login');
    Route::group(['prefix'=>'admin-panel','as'=>'admin.'], function()
    {
        Route::post('hire_form','HireFormController@store')->name('hireForm');
        Route::post('/login', 'AuthController@login')->name('login');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth:admin'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            
            Route::get('wallet-status/{wallet}/{status}','WalletController@status')->name('wallet.status');

            Route::resources([
                'vehicle_type' => 'VehicleTypeController',
                'make' => 'MakeController',
                'vehicle_model' => 'VehicleModelController',
                'rent' => 'RentController',
                'hire' => 'HireController',
                'admin' => 'AdminController',
                'user' =>'UserController',
                'dpr' =>'DprController',
                'slider' => 'SliderController',
                'testimonial' => 'TestimonialController',
                'page' =>'PageController',
                'site_setting' => 'SiteSettingController',
                'wallet'=>'WalletController',
                // 'hire_form'=>'HireFormController',
            ]);
        });
    });

    #Vendor Routes
    Route::group(['prefix'=>'vendor-panel','as'=>'vendor.','namespace'=>'Vendor'], function()
    {
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login')->name('login.post');
        Route::get('/changepassword', 'AuthController@showChangepassword')->name('changepassword');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['middleware' => 'auth'], function()
        {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
            Route::get('company_edit/{user}','UserController@company_edit')->name('company_edit');
            Route::get('bank_edit/{user}','UserController@bank_edit')->name('bank_edit');
            Route::resources([
                'rent'  => 'RentController',
                'hire'  => 'HireController',
                'admin' => 'AdminController',
                'user'  =>'UserController',
                'dpr'   =>'DprController',
                'wallet'=>'WalletController',
            ]);
        });
    });

    
    #FrontEnd Routes
    Route::group(['namespace' => 'Web'], function() {
        Route::get('/','HomeController@index')->name('home');
        Route::get('Contact','ContactController@contact')->name('Contact');
        Route::get('Vendor/signin','VendorSignController@vendorsign')->name('Vendor.signin');
        Route::post('Vendor/store','VendorSignController@store')->name('Vendor.store');
        Route::get('rentalProduct','ProductController@rentalProduct')->name('rentalProduct');
        
        Route::group(['middleware' => 'vendor'], function(){
            Route::get('hire/{rent}','HireController@hire')->name('hire');
            Route::post('hire','HireController@store')->name('hire.store');
        });
        
        Route::get('{page:slug}','PageController@show')->name('page.show');
    });


});

resources/views/backend/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url('admin/css/all.min.css')}}">
    <link rel="stylesheet" href="{{url('admin/css/style.css')}}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    <title>@yield('site_title') | Rent & Hire</title>
</head>
<body>
    
    @yield('main_content')

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
    <script src="{{url('admin/js/script.js')}}"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/datatables-demo.js"></script>

    <script>
        tinymce.init({
          selector: '#mytextarea',
          plugins: [
            'a11ychecker','advlist','advcode','advtable','autolink','checklist','export',
            'lists','link','image','charmap','preview','anchor','searchreplace','visualblocks',
            'powerpaste','fullscreen','formatpainter','insertdatetime','media','table','help','wordcount'
          ],
          toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
            'alignleft aligncenter alignright alignjustify | ' +
            'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
        });
    </script>

</body>
</html>

resources/views/backend/layout/inner.blade.php
@extends('backend.layout.app')

@section('site_title','Dashboard')

@section('main_content')

<body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Rent & Hire</a>
            <!-- Navbar-->
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <ul class="navbar-nav d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{{ route('admin.site_setting.edit',[1]) }}">Site Setting</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{route('admin.changepassword')}}">Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('admin.logout') }}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <x-admin.nav-sidebar />
            <div id="layoutSidenav_content">

                @yield('content')

                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">

                            <div class="text-muted">Design and Developed by <a href="https://suncitytechno.com/">Suncity Techno Solution</a></div>
                            
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            
                        </div>
                    </div>
                </footer>
            </div>
        </div>
</body>




@endsection